In [1]:
import pandas as pd 
import numpy as np 

In [3]:
df = pd.read_csv("homeprices.csv")

In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


In [7]:
df.shape

(6, 4)

In [8]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
df.columns

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [11]:
df['bedrooms']

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [12]:
df['bedrooms'].median()

4.0

In [15]:
df['bedrooms'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
Name: bedrooms, dtype: bool

In [18]:
df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].median())

In [19]:
df['bedrooms']

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [20]:
df_new = df.drop('price', axis='columns')

In [21]:
df_new

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [22]:
price = df['price']

In [24]:
print(price)

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64


In [25]:
X, y = df_new, price

In [26]:
X

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [27]:
from sklearn.model_selection import train_test_split 

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()

In [31]:
model.fit(X_train, y_train)

LinearRegression()

In [32]:
y_pred = model.predict(X_test)

In [33]:
y_pred

array([462391.30434782, 599347.82608695])

In [34]:
y_test

0    550000
4    760000
Name: price, dtype: int64

In [35]:
model.coef_

array([-5.21739130e+01,  2.15869565e+05,  1.84782609e+04])

In [36]:
model.intercept_

-419130.43478266196

In [38]:
model.predict([[3100, 4, 16]])

C:\Users\Hammad\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578260.86956521])